# Supabase local development settings.
[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table RPC. Setting this to 0 removes the limit.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
refresh_token_rotation_enabled = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires refresh_token_rotation_enabled to be false.
# refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true
# Controls whether the confirmation email is also sent when users update their email address.
secure_email_change_enabled = true

# Use OTP instead of magic links for email authentication
[auth.email.template.confirmation]
subject = "🔢 Your Buddy Ride Verification Code - {{ .Token }}"
content_path = "./supabase/email-templates/confirmation.html"

[auth.email.template.recovery]
subject = "🔐 Password Reset Code: {{ .Token }} - Buddy Ride"
content_path = "./supabase/email-templates/recovery.html"

[auth.email.template.magic_link]
subject = "🔢 Your Buddy Ride Login Code: {{ .Token }}"
content_path = "./supabase/email-templates/magic_link.html"

[auth.email.template.invite]
subject = "🎉 You're Invited to Join Buddy Ride!"
content_path = "./supabase/email-templates/invite.html"

[auth.email.template.email_change]
subject = "📧 Confirm Your Email Change - Buddy Ride"
content_path = "./supabase/email-templates/email_change.html"

# Configure OTP as the primary authentication method
[auth.email.template.otp]
subject = "🔢 Your Buddy Ride Code: {{ .Token }}"
content_path = "./supabase/email-templates/otp.html"

# IMPORTANT: Enable OTP-first authentication
[auth.email.otp_exp] 
duration = 3600  # OTP expires in 1 hour

[auth.email.otp_length] 
length = 6  # 6-digit OTP codes

# Rate limiting
[auth.rate_limits.token_refresh]
max_frequency = 60

[auth.rate_limits.email]
max_frequency = 360

# External email configuration
[auth.external.email]
enabled = false

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[functions]
# pg_net extension enables async networking
verify_jwt = false
